language: node_js
node_js:
  - "lts/*"
notifications:
  email: false

before_install:
  - npm install --global lerna nyc mocha typescript@2.7.2
  - cd tools/ && npm install && cd ..

install:
  - lerna bootstrap --hoist

script:
    echo 'Begin daily build'
  - npm run test:travis

cache:
  directories:
    - "node_modules"
    - "tools/node_modules"